version: '2'
services:
    application:
        container_name: seminar_application
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: seminar_workspace
        restart: always
        image: framgia/laravel-workspace
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: seminar_php-fpm
        restart: always
        image: framgia/laravel-php-fpm
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace
    nginx:
          container_name: seminar_nginx
          restart: always
          image: framgia/laravel-nginx
          volumes_from:
              - data
              - application
          ports:
              - "8000:80"
          links:
              - php-fpm
    data:
        container_name: seminar_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    mysql:
        container_name: seminar_mysql
        restart: always
        image: mysql
        volumes_from:
            - data
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
    redis:
        container_name: seminar_redis
        restart: always
        image: redis
        expose:
            - "6379"
        volumes_from:
            - data